Areas/Admin/Controllers/CategoryController.cs
using System.Linq;
using System.Threading.Tasks;
using delicio_app.Data;
using delicio_app.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace delicioapp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller{
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index(){
            return View(await _db.Categories.ToListAsync());
        }

        public IActionResult Create(){
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category){
            if(ModelState.IsValid){
                _db.Categories.Add(category);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
    
        public async Task<IActionResult> Edit(int? id){
            if(id == null){
                return NotFound();
            }

            Category category = await _db.Categories.FindAsync(id);
            if(category == null){
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category){
            if(ModelState.IsValid){
                _db.Update(category);
                await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        public async Task<IActionResult> Delete(int? id){
            if(id == null){
                return NotFound();
            }

            Category category = await _db.Categories.FindAsync(id);
            if(category == null){
                return NotFound();
            }

            return View(category);
        }
    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id){
            Category category = await _db.Categories.FindAsync(id);

            if(category == null)
                return View();

            _db.Categories.Remove(category);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    
        //GET - DETAILS
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _db.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
    }
}

Areas/Admin/Controllers/SubCategoryController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using delicio_app.Data;
using delicio_app.Models;
using delicio_app.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace delicioapp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SubCategoryController : Controller 
    {
        private readonly ApplicationDbContext _db;

        [TempData]
        public string StatusMessage { get; set; }

        public SubCategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index(){
            var subCategories = await _db.SubCategories.Include(s => s.Category).ToListAsync();
            return View(subCategories);
        }

        public async Task<IActionResult> Create(){
            CategoriesViewModel model = new CategoriesViewModel{
                CategoryList = await _db.Categories.ToListAsync(),
                SubCategory = new SubCategory(),
                SubCategoryList = await _db.SubCategories.OrderBy(x => x.Name).Select(m => m.Name).Distinct().ToListAsync(),
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoriesViewModel model){
            if(ModelState.IsValid){
                var doesSubCategoryExists = _db.SubCategories.Include(m => m.Category).Where(x => x.Name == model.SubCategory.Name && x.CategoryID == model.SubCategory.CategoryID);

                if(doesSubCategoryExists.Any()){
                    StatusMessage = "Error: Sub Category already exists under " + doesSubCategoryExists.First().Category.Name + " category. Please use another name!";
                }else{
                    _db.SubCategories.Add(model.SubCategory);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            var viewModel = new CategoriesViewModel{
                CategoryList = await _db.Categories.ToListAsync(),
                SubCategory = model.SubCategory,
                SubCategoryList = await _db.SubCategories.OrderBy(x => x.Name).Select(m => m.Name).ToListAsync(),
                StatusMessage = StatusMessage,
            };
            return View(viewModel);
        }

        [ActionName("GetSubCategory")]
        public async Task<IActionResult> GetSubCategory(int id){
            List<SubCategory> subCategories = new List<SubCategory>();
            subCategories = await _db.SubCategories.Where(x => x.CategoryID == id).ToListAsync();
            return Json(new SelectList(subCategories, "ID", "Name"));
        }

        public async Task<IActionResult> Edit(int? id){
            if(id == null){
                return NotFound();
            }

            SubCategory subCategory = await _db.SubCategories.SingleOrDefaultAsync(x => x.ID == id);

            if(subCategory == null){
                return NotFound();
            }

            CategoriesViewModel model = new CategoriesViewModel{
                CategoryList = await _db.Categories.ToListAsync(),
                SubCategory = subCategory,
                SubCategoryList = await _db.SubCategories.OrderBy(x => x.Name).Select(m => m.Name).Distinct().ToListAsync(),
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CategoriesViewModel model){
            if(ModelState.IsValid){
                var doesSubCategoryExists = _db.SubCategories.Include(m => m.Category).Where(x => x.Name == model.SubCategory.Name && x.CategoryID == model.SubCategory.CategoryID);

                if(doesSubCategoryExists.Any()){
                    StatusMessage = "Error: Sub Category already exists under " + doesSubCategoryExists.First().Category.Name + " category. Please use another name!";
                }
                else
                {
                    SubCategory subCategoryInDB = await _db.SubCategories.FindAsync(id);
                    subCategoryInDB.Name = model.SubCategory.Name;

                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            var viewModel = new CategoriesViewModel{
                CategoryList = await _db.Categories.ToListAsync(),
                SubCategory = model.SubCategory,
                SubCategoryList = await _db.SubCategories.OrderBy(x => x.Name).Select(m => m.Name).ToListAsync(),
                StatusMessage = StatusMessage,
            };
            return View(viewModel);
        }
    
        //GET Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var subCategory = await _db.SubCategories.Include(s => s.Category).SingleOrDefaultAsync(m => m.ID == id);
            if (subCategory == null)
            {
                return NotFound();
            }

            return View(subCategory);
        } 
    }
}

Views/Shared/_CreateAndBackButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info">Create New &nbsp;
        <i class="fas fa-plus"></i>
    </a>
</p>

Views/Shared/_DeleteAndBackButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="Delete">
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Views/Shared/_DetailsAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <a asp-action="Edit" asp-route-id="@Model" class="btn btn-info form-control">Edit</a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Views/Shared/_EditAndBackButton.cshtml
@model int
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" asp-route-id="@Model" value="Update">
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - delicio_app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/4496964e2d.js" crossorigin="anonymous"></script>
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DELICIO</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown text-white-50">
                            <a href="#" class="nav-link dropdown-toggle" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Content Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Category</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">Sub Category</a>
                                <a href="#" class="dropdown-item">Menu Item</a>
                                <a href="#" class="dropdown-item">Coupons</a>
                                <a href="#" class="dropdown-item">Users</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color: #343a40">
        <div class="container">
            &copy; 2021 - DELICIO
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Views/Shared/_TableButtonsPartial.cshtml
@model int

<td style="width: 150px;">
    <div class="btn-group" role='group'>
        <a class='btn btn-primary text-white' asp-action='Edit' asp-route-id='@Model'>
            <i class="fas fa-edit"></i>
        </a>

        <a class='btn btn-success text-white' asp-action='Details' asp-route-id='@Model'>
            <i class="fas fa-list-alt"></i>
        </a>

        <a class='btn btn-danger text-white' asp-action='Delete' asp-route-id='@Model'>
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td> 